{
 "title": "(Home) Kubernetes Integration",
 "tags": [
  "kubernetes-integration",
  "Start Here"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up{job!=\"\"}, cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kubelet_runtime_operations_total{cluster=\"$cluster\", job!=\"\"}, instance)"
    }
   },
   { "name": "lokids", "label": "Events Data Source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"padding: 10px;\">\n  <div style=\"margin-bottom: 30px;display: flex; flex-direction: row; align-items: center; margin-top: 10px;\">\n    <img style=\"height: 40px; width: 40px; margin-right: 10px;\" src=\"https://storage.googleapis.com/grafanalabs-integration-logos/kubernetes.svg\" />\n    <h2 style=\"margin-top: 5px;\">Welcome to Grafana Cloud for Kubernetes</h2>\n  </div>\n  <div style=\"display: flex; width: 100%;\">\n    <div style=\"width: 50%;\">\n      <div style=\"margin: 0 0 10px 0;display: flex; \">\n        <img style=\"margin-right: 20px; margin-top: 10px; height: 25px;\" src=\"https://storage.googleapis.com/k8s-integration-icons/compass.png\" alt=\"\">\n        <p style=\"width: 80%; margin-top: 5px;\">Visualize and query cAdvisor, Kubelet and kube-state-metrics for your K8s cluster(s)</p>\n      </div>\n      <div style=\"margin: 10px 0 10px 0;display: flex; \">\n        <img style=\"margin-right: 20px; margin-top: 10px; height: 25px;\" src=\"https://storage.googleapis.com/k8s-integration-icons/dash.png\" alt=\"\">\n        <p style=\"width: 80%; margin-top: 5px;\">Access premade dashboards for visibility into resource consumption and cluster operations</p>\n      </div>\n    </div>\n    <div style=\"width: 50%; margin-top: 0;\">\n      <div style=\"margin: 0 0 10px 0; display: flex; \">\n        <img style=\"margin-right: 20px; margin-top: 10px; height: 25px;\" src=\"https://storage.googleapis.com/k8s-integration-icons/bell.png\" alt=\"\">\n        <p style=\"width: 80%; margin-top: 5px;\">Create alerts based on cAdvisor and kube-state-metrics in Grafana Cloud Alerting</p>\n      </div>\n      <div style=\"margin: 0 0 10px 0; display: flex; \">\n        <img style=\"margin-right: 20px; margin-top: 10px; height: 25px;\" src=\"https://storage.googleapis.com/k8s-integration-icons/loki.svg\" alt=\"\">\n        <p style=\"width: 80%; margin-top: 5px;\">Collect and ship Pod logs to Grafana Cloud. Learn more <a href=\"https://grafana.com/docs/grafana-cloud/quickstart/agent-k8s/k8s_agent_logs/\" target=\"_blank\">here</a>.</p>\n      </div>\n    </div>\n  </div>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Configuration status",
   "type": "stat",
   "description": "Red = Missing, Amber = Duplicate, Green = OK",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (cluster) (\n    count by (cluster, node) (kubelet_node_name{cluster=\"$cluster\"}) > 1 OR\n    topk(1, kubelet_node_name{cluster=\"$cluster\"}) OR\n    1-absent(kubelet_node_name{cluster=\"$cluster\"})\n)",
     "legendFormat": "Kubelet"
    },
    {
     "expr": "max by (cluster) (\n    count by (cluster, node) (kube_node_info{cluster=\"$cluster\"}) > 1 OR\n    topk(1, kube_node_info{cluster=\"$cluster\"}) OR\n    1-absent(kube_node_info{cluster=\"$cluster\"})\n)",
     "legendFormat": "Kube State Metrics"
    },
    {
     "expr": "max by (cluster) (\n    count by (cluster, instance) (machine_memory_bytes{cluster=\"$cluster\"} /\n        machine_memory_bytes{cluster=\"$cluster\"}) > 1 OR\n    topk(1, machine_memory_bytes{cluster=\"$cluster\"} /\n        machine_memory_bytes{cluster=\"$cluster\"}) OR\n    1-absent(machine_memory_bytes{cluster=\"$cluster\"})\n)",
     "legendFormat": "cAdvisor"
    },
    {
     "expr": "max by (cluster) (\n    count by (cluster, instance) (node_cpu_seconds_total{cpu=\"0\", mode=\"idle\", cluster=\"$cluster\"} /\n        node_cpu_seconds_total{cpu=\"0\", mode=\"idle\", cluster=\"$cluster\"}) > 1 OR\n    topk(1, node_cpu_seconds_total{cpu=\"0\", mode=\"idle\", cluster=\"$cluster\"} /\n        node_cpu_seconds_total{cpu=\"0\", mode=\"idle\", cluster=\"$cluster\"}) OR\n    1-absent(node_cpu_seconds_total{cpu=\"0\", mode=\"idle\", cluster=\"$cluster\"})\n)",
     "legendFormat": "Node Exporter"
    }
   ]
  },
  {
   "title": "Running pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_pods{cluster=\"$cluster\", job!=\"\", instance=~\"$instance\"}) OR sum(kubelet_running_pod_count{cluster=\"$cluster\", job!=\"\", instance=~\"$instance\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_containers{cluster=\"$cluster\", job!=\"\", instance=~\"$instance\"}) OR sum(kubelet_running_container_count{cluster=\"$cluster\", job!=\"\", instance=~\"$instance\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
   "options": {
    "content": "<h3>Resource consumption visibility</h3>\n<p>We provide 7 pre-built dashboards that give you visibility into resource consumption, with drilldowns by cluster, Namespace, Pod, Node and more.</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster CPU usage (by Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Resource consumption visibility",
   "type": "dashlist",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "options": {
    "content": "<h3>Cluster operations visibility</h3>\n<p>We provide 2 pre-built dashboards that give you visibility into the operations of your K8s clusters, including Kubelet metrics and Persistent Volumes.</p>\n<a href=\"https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/\" target=\"_blank\">Read more about Kubelet ></a>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Events",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "{job!=\"\", cluster=\"$cluster\"} | logfmt | line_format \"{{.kind}} {{.name}}: {{.msg}}\""
    }
   ]
  },
  {
   "title": "Cluster operations visibility",
   "type": "dashlist",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  }
 ]
}